version: '2'

services:
  website:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_SCHEMA}"

